const AppError = require("../middlewares/AppError");
const ProjectModel = require("../models/project.model");
const UserModel = require("../models/user.model");
const WebhookSourceModel = require("../models/webhookSource.model");
const { deriveProjectSetupState } = require("../utils/projectState");
const { createWebhookSource } = require("./webhook.service");

// SERVICE: CREATE PROJECT SERVICE
exports.createProjectService = async (body, userId) => {
  const { name } = body;

  if (!userId) {
    throw new AppError("Authentication required", 401, "AUTH_REQUIRED");
  }

  if (!name) {
    throw new AppError(
      "Project name is required",
      400,
      "PROJECT_NAME_REQUIRED"
    );
  }

  const project = await ProjectModel.create({
    name: body.name,
    userId,
    setup: {
      inputProvider: null,
      providerConfigured: false,
      destinationConfigured: false,
      completedAt: null,
    },
  });

  return {
    project: {
      id: project._id,
      name: project.name,
      setupState: deriveProjectSetupState(project.setup),
      createdAt: project.createdAt,
    },
  };
};

// SERVICE: SELECT INPUT
exports.selectInputProviderService = async (body, userId, projectId) => {
  const { type } = body;

  if (!type || !["webflow", "framer"].includes(type)) {
    throw new AppError(
      "Invalid input provider selected",
      400,
      "INVALID_INPUT_PROVIDER"
    );
  }

  const project = await ProjectModel.findOne({
    _id: projectId,
    userId,
  });

  if (!project) {
    throw new AppError("Project not found", 404, "PROJECT_NOT_FOUND");
  }

  if (project.setup?.completedAt) {
    throw new AppError(
      "Project setup is already completed",
      409,
      "PROJECT_ALREADY_CONFIGURED"
    );
  }

  project.setup = {
    inputProvider: type,
    providerConfigured: false,
    destinationConfigured: false,
    completedAt: null,
  };
  await project.save();

  await WebhookSourceModel.updateMany(
    {
      projectId,
      status: "active",
    },
    {
      status: "disabled",
    }
  );

  const webhook = await createWebhookSource(projectId, (provider = type));

  return {
    setupState: deriveProjectSetupState(project.setup),
    webhookId: webhook._id,
    provider,
    webhookUrl: webhook.endPoint,
    secret: webhook.secret,
    note:
      type === "webflow"
        ? "Paste the secret generated by Webflow into this app."
        : "Copy this secret and paste it into Framer to complete verification.",
  };
};

// SERVICE: SAVE WEBFLOW SECRET KEY
exports.saveWebflowSecretKeyService = async (body, userId, projectId) => {
  const { webhookId, webflowSecretKey } = body;

  if (!webhookId || !webflowSecretKey) {
    throw new AppError(
      "Webhook ID and secret key are required",
      400,
      "REQUIRED_FIELDS_MISSING"
    );
  }

  const project = await ProjectModel.findOne({
    _id: projectId,
    userId,
  });
  if (!project) {
    throw new AppError("Project not found", 404, "PROJECT_NOT_FOUND");
  }

  const webhookSource = await WebhookSourceModel.findOneAndUpdate(
    {
      _id: webhookId,
      projectId,
      provider: "webflow",
      status: "unconfigured",
    },
    {
      secret: webflowSecretKey,
    },
    {
      new: true,
    }
  );

  if (!webhookSource) {
    throw new AppError(
      "Webhook configuration not found or already completed",
      404,
      "WEBHOOK_CONFIGURATION_NOT_FOUND"
    );
  }

  project.setup.providerConfigured = true;
  project.setup.destinationConfigured = false;
  project.setup.completedAt = null;
  await project.save();

  return {
    setupState: deriveProjectSetupState(project.setup),
  };
};

// SERVICE: ADD DESTINATION EMAIL
exports.addDestinaonEmailService = async (body, userId, projectId) => {
  let { destinationEmail, webhookId } = body;

  if (!destinationEmail || !webhookId) {
    throw new AppError(
      "Destination email is required",
      400,
      "DESTINATION_EMAIL_REQUIRED"
    );
  }
  destinationEmail = destinationEmail.trim().toLowerCase();
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(destinationEmail)) {
    throw new AppError(
      "Please enter a valid email address",
      400,
      "INVALID_EMAIL_FORMAT"
    );
  }

  const project = await ProjectModel.findOne({
    _id: projectId,
    userId,
  });
  if (!project) {
    throw new AppError("Project not found", 404, "PROJECT_NOT_FOUND");
  }

  project.output = {
    config: {
      email: destinationEmail,
    },
  };

  project.setup.providerConfigured =
    project.setup.inputProvider === "framer"
      ? true
      : project.setup.providerConfigured;

  project.setup.destinationConfigured = true;
  project.setup.completedAt = new Date();
  await project.save();

  await WebhookSourceModel.updateMany(
    {
      projectId,
      status: "active",
    },
    {
      status: "disabled",
    }
  );

  const webhook = await WebhookSourceModel.findOneAndUpdate(
    {
      _id: webhookId,
      projectId,
      status: "unconfigured",
    },
    {
      status: "active",
    },
    {
      new: true,
    }
  );

  if (!webhook) {
    throw new AppError(
      "Webhook activation failed",
      404,
      "WEBHOOK_ACTIVATION_FAILED"
    );
  }

  await UserModel.updateOne(
    {
      _id: userId,
      hasCompletedProductOnboarding: false,
    },
    {
      hasCompletedProductOnboarding: true,
    }
  );

  return {
    setupState: deriveProjectSetupState(project.setup),
  };
};
